### ISSUE TITLE
Should pa_autoconfigure_django.py make modifications to settings.py? Can this be avoided somehow?

### ISSUE THREAD

**Issue by das-g** [pythonanywhere/helper_scripts#27]
Should `pa_autoconfigure_django.py` make modifications to `settings.py` when used as layed out [in the Django Girls tutorial](https://tutorial.djangogirls.org/en/deploy/#configuring-our-site-on-pythonanywhere)?

TL;DR: The process there is to run on PythonAnywhere
```bash
pip3.6 install --user pythonanywhere
pa_autoconfigure_django.py --python=3.6 ${URL_OF_OWN_REPO}.git
```

Can this modification of files in the repo be avoided somehow?

This came up in DjangoGirls/tutorial#1640 and I think I've also had participants of the DjangoGirls workshops experience unexpected changes to their repo on PythonAnywhere.

**Comment by millenniumhand** [comment]
We can be smarter about how we make changes to the  settings files so that we do not make changes unnecessarily. I'll have a look at this tomorrow.

**Comment by millenniumhand** [comment]
The settings that are set (ALLOWED_HOSTS, MEDIA_URL, STATIC_ROOT and MEDIA_ROOT) do need to be set for the site to work on PythonAnywhere. 

I have modified the script so that it only add those settings if they are not present in the settings file to start with. That will ensure that a new project will have the correct settings and using the script on a project that already has those settings will not modify the settings file.
