### ISSUE TITLE
How to update npm to latest on bash console?

### ISSUE THREAD

**Issue by ameybhavsar24** [pythonanywhere/helper_scripts#28]
On my bash console, I have `npm@4.3.0` and `node@8.11.4`.
I needed the latest version to support some packages which need at least Node 10+.
I did:
```
npm install -g npm
```
which did not work since I am not root/Administrator.
How to update both of them to latest?

**Comment by ameybhavsar24** [comment]
Found a way https://help.pythonanywhere.com/pages/Node/
Closing this issue.
Curious to know why default version is so low.

**Comment by gpjt** [comment]
It's an old version just because that is the default for the operating system your account is using (Ubuntu 16.04).

BTW this repository relates to a set of useful helper scripts to make using PythonAnywhere from a command-line easier, and isn't really the right place for questions about PythonAnywhere itself.  You can ask questions about PythonAnywhere on [our forums](https://www.pythonanywhere.com/forums/), by using the "Send feedback" link on our site, or by email to support@pythonanywhere.com.
